name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: curl -s "https://api.render.com/deploy/srv-d6srhl14tr6s738214tg?key=jrV_pAgzRw4"
